---
- name: Configuring Firewall on servers
  hosts: servers
  become: true

  tasks:
   - name: Install Firewall
     ansible.builtin.dnf:
       name: firewalld
       state: present

   - name: Enable Firewall
     ansible.builtin.systemd_service:
       name: firewalld
       state: started
       enabled: true

   - name: Disabling external SSH in both servers
     ansible.posix.firewalld:
       state: disabled
       service: ssh
       permanent: true
       zone: public
       immediate: true

   - name: Enabling HTTP in both servers       
     ansible.posix.firewalld:
       state: enabled
       service: http       
       permanent: true
       zone: public
       immediate: true

   - name: Disabling cockpit
     ansible.posix.firewalld:
       state: disabled
       service: cockpit
       immediate: true
       permanent: true 

   - name: allow port 8080 TCP for Podman
     ansible.posix.firewalld:
       state: enabled
       port: 8080/tcp
       permanent: true
       immediate: true
   
   - name: Allow SSH from Ansible control node only
     ansible.posix.firewalld:
       rich_rule: 'rule family="ipv4" source address="192.168.56.20" port port="22" protocol="tcp" accept'
       state: enabled
       permanent: true
       immediate: true
