---
- name: Creating and Managing Podman Containers
  hosts: servers
  become: true

  tasks:
   - name: Run Container
     containers.podman.podman_container:
       name: apache-container  
       image: docker.io/library/httpd:latest  
       state: started
       publish: "8080:80"
